CXX = g++
CFLAGS = -g --std=c++11 -I/home/anandps/local/adolc/include -L/home/anandps/local/adolc/lib64 -ladolc -larmadillo -lgfortran -I/home/anandps/local/armadillo/usr/include -L/home/anandps/local/armadillo/usr/lib

all:
	$(CXX) main.cpp -o main $(CFLAGS)
clean:
	rm main
